### ISSUE TITLE
Why not polling?

### ISSUE THREAD

**Issue by pietercolpaert** [maercky/parkings-app#1]
Hi @maercky,

You indicate yourself in the README.md that you don't know whether it's the way to go, so hence my question: the publishing server only updates the data each ~ 1 minute... Why don't you just poll the data each minute instead of heaving a pub-sub mechanism?

Your code seems very interesting though and cool that you're reusing the open data from the city of Ghent!

**Comment by maercky** [comment]
Hi @pietercolpaert 

I admit, maybe that's a better way to go, since it may be a little overkill to check every X seconds when the jsonstream only is updated once every minute.

However, in the long run, a wild idea of mine is to build a real version of the [Marauder's Map](http://harrypotter.wikia.com/wiki/Marauder's_Map) with realtime moving markers on a map, based on several realtime data-streams I can't control/hook (external systems, eg. Swarm, Google Calendar, API of a wifi access point, chat-app statuses, ...) and some other datasets I can set a hook on. I only want to fetch and update the data whenever it changes, like immediately (and by data, I mean the diff so the whole app doesn't need a rebuild). The result will be a map-app, where the data really is served realtime (wishful thinking: "no delays"), whenever something changes in one the datasets and eg. you'll see the marker (the person) moving (walking) in realtime on a map.
This may be my project on the side this summer :)

Since I had no mentionable experience with Node.js, Sockets or Angular, I thought of this mini-experiment to try and play with these technologies and see what was possible to serve realtime json in an Angular-app :-)

**Comment by pietercolpaert** [comment]
Alright! Cool stuff :-)
